### ISSUE TITLE
'ascii' codec can't encode character u'\xe9' in position 36

### ISSUE THREAD

**Issue by ThatcherC** [powerapi/powerapi-python#1]
This error comes up after what seems to be an otherwise successful login. Have you encounter this before? Here's the full error - 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "powerapi/core.py", line 68, in auth
    return user(self, r.text)
  File "powerapi/user.py", line 9, in __init__
    self.courses = self._createCourses()
  File "powerapi/user.py", line 16, in _createCourses
    courses.append(course(self.core, item.groups()[1]))
  File "powerapi/course.py", line 8, in __init__
    self._populateCourse()
  File "powerapi/course.py", line 15, in _populateCourse
    'name': courseData.groups()[4].encode('ascii'),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 36: ordinal not in range(128)
```

-Thatcher

**Comment by unlobito** [comment]
Hm, seems I'm unable to reproduce this on my end. Then again, PowerSchool installs can very quite a bit between schools.

Any chance you could drop me an email with the contents of your /guardian/home.html? (post-login, of course)
My email's listed in my github profile.
